repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.961'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --install-types, --non-interactive]
