name: release
on:
  push:
    branches:
     - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - uses: rymndhng/release-on-push-action@v0.25.0 # https://github.com/marketplace/actions/tag-release-on-push-action
    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
