name: test-suite
on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8.16', '3.9.12' ] # TODO add more later on
    name: Python ${{ matrix.python-version }} test
    steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
     - run: make static-analysis test-suite
     # - uses: actions/upload-artifact@v3 # todo -- this would use some easily displayable artifact
     #   with:
     #     name: code-coverage-report
     #     path: htmlcov
     #     retention-days: 7
